services:

  gc-front:
    image: coderlady/gc-front:0.0.1
    container_name: gc-front
    restart: always
    pull_policy: always
    ports:
      - 91:80
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network
